#generate n + 1 equally spaced x coordinates in the interval [a,b], store coordinates in a lis

# start w/ empty list
#use for loop to append each coordinate to the list

#w/ n intervals, corresponding to n + 1 points
#in [a, b] each interval has length h = (b - a)/n
#coordinates can be generated by the fomula xi = a+ ih, where i = 0,...,n . 

#b. use list comprehension (section 2.3.5).


a = 1
b = 2

n = 20
h = (b - a) / n #step size

i = []
coordinates = []

print (f'For x in [1, 2] with {n} intervals, the interval length is h = {h}, and')    #explanation of variables

print (f'Using a for loop:')


for i in range(n+1):
    xi = a + i*h 
    coordinates.append(xi)
    
print (f'x = {coordinates}')



print (f'Using list comprehensions:')

new_coordinates = [
    a + coordinates * h
    for coordinates in range(n +1)
]

print (f'x = {new_coordinates}')